### ISSUE TITLE
Build error with pip 

### ISSUE THREAD

**Issue by JSun950313** [google-deepmind/mujoco_mpc#222]
I tried to use pip install mujoco_mpc/python/  to install it on Ubuntu 20 and the version of Python is 3.8.10 and the version of mujoco-src downloads automatically is 3.0.1. It reports some errors as follow:

```
Processing ./mujoco_mpc/python
  Preparing metadata (setup.py) ... done
Requirement already satisfied: grpcio in ./venv/lib/python3.8/site-packages (from mujoco-mpc==0.1.0) (1.59.3)
Requirement already satisfied: mujoco>=2.3.3 in ./venv/lib/python3.8/site-packages (from mujoco-mpc==0.1.0) (3.0.1)
Requirement already satisfied: protobuf in ./venv/lib/python3.8/site-packages (from mujoco-mpc==0.1.0) (4.25.1)
Requirement already satisfied: absl-py in ./venv/lib/python3.8/site-packages (from mujoco>=2.3.3->mujoco-mpc==0.1.0) (2.0.0)
Requirement already satisfied: etils[epath] in ./venv/lib/python3.8/site-packages (from mujoco>=2.3.3->mujoco-mpc==0.1.0) (1.3.0)
Requirement already satisfied: glfw in ./venv/lib/python3.8/site-packages (from mujoco>=2.3.3->mujoco-mpc==0.1.0) (2.6.3)
Requirement already satisfied: numpy in ./venv/lib/python3.8/site-packages (from mujoco>=2.3.3->mujoco-mpc==0.1.0) (1.24.4)
Requirement already satisfied: pyopengl in ./venv/lib/python3.8/site-packages (from mujoco>=2.3.3->mujoco-mpc==0.1.0) (3.1.7)
Requirement already satisfied: importlib_resources in ./venv/lib/python3.8/site-packages (from etils[epath]->mujoco>=2.3.3->mujoco-mpc==0.1.0) (6.1.1)
Requirement already satisfied: typing_extensions in ./venv/lib/python3.8/site-packages (from etils[epath]->mujoco>=2.3.3->mujoco-mpc==0.1.0) (4.8.0)
Requirement already satisfied: zipp in ./venv/lib/python3.8/site-packages (from etils[epath]->mujoco>=2.3.3->mujoco-mpc==0.1.0) (3.17.0)
Building wheels for collected packages: mujoco-mpc
  Building wheel for mujoco-mpc (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [382 lines of output]
      /home/jsun/Mo/venv/lib/python3.8/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_py
      running generate_proto_grpc
      touch /home/jsun/Mo/mujoco_mpc/python/build/lib.linux-x86_64-cpython-38/mujoco_mpc/proto/__init__.py
      running copy_task_assets
      copying mujoco_mpc/ui_agent_test.py -> build/lib.linux-x86_64-cpython-38/mujoco_mpc
      copying mujoco_mpc/direct.py -> build/lib.linux-x86_64-cpython-38/mujoco_mpc
      copying mujoco_mpc/agent_test.py -> build/lib.linux-x86_64-cpython-38/mujoco_mpc
      copying mujoco_mpc/filter_test.py -> build/lib.linux-x86_64-cpython-38/mujoco_mpc
      copying mujoco_mpc/mjpc_parameters.py -> build/lib.linux-x86_64-cpython-38/mujoco_mpc
      copying mujoco_mpc/filter.py -> build/lib.linux-x86_64-cpython-38/mujoco_mpc
      copying mujoco_mpc/direct_test.py -> build/lib.linux-x86_64-cpython-38/mujoco_mpc
      copying mujoco_mpc/agent.py -> build/lib.linux-x86_64-cpython-38/mujoco_mpc
      copying mujoco_mpc/__init__.py -> build/lib.linux-x86_64-cpython-38/mujoco_mpc
      running build_ext
      Configuring CMake with the following arguments:
        -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE
        -DCMAKE_BUILD_TYPE:STRING=Debug
        -DBUILD_TESTING:BOOL=OFF
        -DMJPC_BUILD_GRPC_SERVICE:BOOL=ON
      CHECK_STARTmujoco::FindOrFetch: checking for targets in package `mujoco`
      CHECK_FAILtarget `mujoco::mujoco` not defined.
      CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve `mujoco`
      CHECK_STARTmujoco::FindOrFetch: checking for targets in package `qhull`
      CHECK_FAILtarget `qhull` not defined.
      CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve `qhull`
      --
      -- ========== qhull Build Information ==========
      -- Build Version:                             8.1-alpha1
      -- Install Prefix (CMAKE_INSTALL_PREFIX):     /usr/local
      -- Binary Directory (BIN_INSTALL_DIR):        bin
      -- Library Directory (LIB_INSTALL_DIR):       lib
      -- Include Directory (INCLUDE_INSTALL_DIR):   include
      -- Documentation Directory (DOC_INSTALL_DIR): share/doc/qhull
      -- Man Pages Directory (MAN_INSTALL_DIR):     share/man/man1
      -- CMake Directory (CMAKE_INSTALL_DIR):       lib/cmake/QHull
      -- PkgConfig Directory (PKGCONFIG_INSTALL_DIR):lib/pkgconfig
      -- Build Type (CMAKE_BUILD_TYPE):             Debug
      -- Build static libraries:                    ON
      -- Build shared library:                      OFF
      -- Use shared library for linking apps:       OFF
      -- Build tests:                                OFF
      -- To override these options, add -D{OPTION_NAME}=... to the cmake command
      --   Build the debug targets                  -DCMAKE_BUILD_TYPE=Debug
      --
      -- To build and install qhull, enter "make" and "make install"
      -- To smoketest qhull, enter "ctest"
      --
      CHECK_PASSDone
      CHECK_STARTmujoco::FindOrFetch: checking for targets in package `tinyxml2`
      CHECK_FAILtarget `tinyxml2` not defined.
      CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve `tinyxml2`
      CHECK_PASSDone
      CHECK_STARTmujoco::FindOrFetch: checking for targets in package `tinyobjloader`
      CHECK_FAILtarget `tinyobjloader` not defined.
      CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve `tinyobjloader`
      CHECK_PASSDone
      CHECK_STARTmujoco::FindOrFetch: checking for targets in package `sdflib`
      CHECK_FAILtarget `SdfLib` not defined.
      CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve `sdflib`
      -- GLM is a header only library, no need to build it. Set the option GLM_TEST_ENABLE with ON to build and run the test bench
      -- Build spdlog: 1.9.2
      -- Build type: Debug
      CHECK_PASSDone
      CHECK_STARTmujoco::FindOrFetch: checking for targets in package `ccd`
      CHECK_FAILtarget `ccd` not defined.
      CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve `ccd`
      CMake Warning (dev) at build/_deps/ccd-src/CMakeLists.txt:9 (project):
        Policy CMP0048 is not set: project() command manages VERSION variables.
        Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
        command to set the policy and suppress this warning.
      
        The following variable(s) would be set to empty:
      
          PROJECT_VERSION
          PROJECT_VERSION_MAJOR
          PROJECT_VERSION_MINOR
          PROJECT_VERSION_PATCH
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      CHECK_PASSDone
      CHECK_STARTmujoco::FindOrFetch: checking for targets in package `mujoco`
      CHECK_PASSfound
      CHECK_STARTmujoco::FindOrFetch: checking for targets in package `glfw3`
      CHECK_FAILtarget `glfw` not defined.
      CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve `glfw3`
      -- Using X11 for window creation
      CHECK_PASSDone
      CHECK_PASSDone
      CHECK_STARTmujoco::FindOrFetch: checking for targets in package `GTest`
      CHECK_FAILtarget `gtest` not defined.
      CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve `googletest`
      CHECK_PASSDone
      CHECK_STARTmujoco::FindOrFetch: checking for targets in package `absl`
      CHECK_FAILtarget `absl::core_headers` not defined.
      CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve `abseil-cpp`
      CHECK_PASSDone
      CHECK_STARTmujoco::FindOrFetch: checking for targets in package `glfw`
      CHECK_PASSfound
      CHECK_STARTmujoco::FindOrFetch: checking for targets in package `gRPC`
      CHECK_FAILtarget `gRPC` not defined.
      CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve `gRPC`
      CMake Warning at build/_deps/grpc-src/third_party/protobuf/cmake/CMakeLists.txt:3 (message):
        Calling of cmake with source directory set to "cmake" subdirectory of
        Protocol Buffers project is deprecated.  Top-level directory of Protocol
        Buffers project should be used instead.
      
      
      --
      -- 3.21.12.0
      -- Checking for module 'libsystemd'
      --   No package 'libsystemd' found
      CHECK_PASSDone
      We need the following for agent/direct_protos:
      _GRPC_CPP_PLUGIN_EXECUTABLE$<TARGET_FILE:grpc_cpp_plugin>
      AGENT_SERVICE_COMPILE_OPTIONS=
      AGENT_SERVICE_COMPILE_OPTIONS=
      DIRECT_SERVICE_COMPILE_OPTIONS=
      FILTER_SERVICE_COMPILE_OPTIONS=
      -- Configuring done
      CMake Warning (dev) at build/_deps/grpc-src/third_party/cares/cares/src/lib/CMakeLists.txt:67 (ADD_LIBRARY):
        Policy CMP0063 is not set: Honor visibility properties for all target
        types.  Run "cmake --help-policy CMP0063" for policy details.  Use the
        cmake_policy command to set the policy and suppress this warning.
      
        Target "c-ares" of type "STATIC_LIBRARY" has the following visibility
        properties set for C:
      
          C_VISIBILITY_PRESET
      
        For compatibility CMake is not honoring them for this target.
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      CMake Warning (dev) at build/_deps/grpc-src/third_party/cares/cares/src/tools/CMakeLists.txt:41 (ADD_EXECUTABLE):
        Policy CMP0063 is not set: Honor visibility properties for all target
        types.  Run "cmake --help-policy CMP0063" for policy details.  Use the
        cmake_policy command to set the policy and suppress this warning.
      
        Target "acountry" of type "EXECUTABLE" has the following visibility
        properties set for C:
      
          C_VISIBILITY_PRESET
      
        For compatibility CMake is not honoring them for this target.
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      CMake Warning (dev) at build/_deps/grpc-src/third_party/cares/cares/src/tools/CMakeLists.txt:24 (ADD_EXECUTABLE):
        Policy CMP0063 is not set: Honor visibility properties for all target
        types.  Run "cmake --help-policy CMP0063" for policy details.  Use the
        cmake_policy command to set the policy and suppress this warning.
      
        Target "adig" of type "EXECUTABLE" has the following visibility properties
        set for C:
      
          C_VISIBILITY_PRESET
      
        For compatibility CMake is not honoring them for this target.
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      CMake Warning (dev) at build/_deps/grpc-src/third_party/cares/cares/src/tools/CMakeLists.txt:7 (ADD_EXECUTABLE):
        Policy CMP0063 is not set: Honor visibility properties for all target
        types.  Run "cmake --help-policy CMP0063" for policy details.  Use the
        cmake_policy command to set the policy and suppress this warning.
      
        Target "ahost" of type "EXECUTABLE" has the following visibility properties
        set for C:
      
          C_VISIBILITY_PRESET
      
        For compatibility CMake is not honoring them for this target.
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- Generating done
      -- Build files have been written to: /home/jsun/Mo/mujoco_mpc/build
      Building `agent_server` and `ui_agent_server` with CMake
      [  0%] Built target qhullstatic_r
      [  0%] Built target lodepng
      [  0%] Built target ccd
      [ 14%] Built target crypto
      [ 14%] Built target tinyxml2
      [ 14%] Built target tinyobjloader
      [ 15%] Built target glfw
      [ 15%] Built target absl_strerror
      [ 15%] Built target absl_spinlock_wait
      [ 15%] Built target absl_log_severity
      [ 17%] Built target absl_civil_time
      [ 17%] Built target absl_int128
      [ 17%] Built target absl_time_zone
      [ 17%] Built target absl_exponential_biased
      [ 17%] Built target absl_log_internal_nullguard
      [ 17%] Built target absl_flags_commandlineflag_internal
      [ 17%] Built target absl_random_seed_gen_exception
      [ 17%] Built target absl_random_internal_platform
      [ 17%] Built target address_sorting
      [ 19%] Built target upb
      [ 22%] Built target c-ares
      [ 26%] Built target libprotobuf
      [ 26%] Built target re2
      [ 28%] Built target ssl
      [ 28%] Built target absl_random_internal_randen_slow
      [ 31%] Built target mujoco
      [ 31%] Built target absl_raw_logging_internal
      [ 31%] Built target absl_random_internal_randen_hwaes_impl
      [ 33%] Built target platform_ui_adapter
      [ 33%] Built target absl_throw_delegate
      [ 33%] Built target absl_base
      [ 38%] Built target libprotoc
      [ 38%] Built target absl_debugging_internal
      [ 38%] Built target absl_bad_variant_access
      [ 38%] Built target absl_bad_optional_access
      [ 38%] Built target absl_cordz_functions
      [ 39%] Built target absl_crc_cpu_detect
      [ 39%] Built target absl_random_internal_randen_hwaes
      [ 39%] Built target absl_log_internal_conditions
      [ 39%] Built target protoc
      [ 39%] Built target threadpool
      [ 39%] Built target grpc_plugin_support
      [ 41%] Built target absl_malloc_internal
      [ 41%] Built target absl_string_view
      [ 41%] Built target absl_stacktrace
      [ 41%] Built target absl_strings_internal
      [ 41%] Built target absl_demangle_internal
      [ 41%] Built target absl_graphcycles_internal
      [ 41%] Built target absl_city
      [ 41%] Built target absl_low_level_hash
      [ 41%] Built target absl_crc_internal
      [ 41%] Built target absl_random_internal_randen
      [ 42%] Built target absl_strings
      [ 42%] Built target grpc_cpp_plugin
      [ 42%] Built target agent_state_proto_lib
      [ 42%] Built target absl_symbolize
      [ 42%] Built target absl_hash
      [ 42%] Built target absl_time
      [ 42%] Built target absl_str_format_internal
      [ 42%] Built target absl_flags_commandlineflag
      [ 42%] Built target absl_log_internal_proto
      [ 42%] Built target absl_random_distributions
      [ 42%] Built target absl_random_internal_seed_material
      [ 42%] Built target absl_crc32c
      [ 42%] Built target absl_kernel_timeout_internal
      [ 42%] Built target absl_examine_stack
      [ 42%] Built target absl_flags_private_handle_accessor
      [ 44%] Built target absl_flags_marshalling
      [ 44%] Built target absl_log_internal_globals
      [ 46%] Built target absl_log_entry
      [ 46%] Built target absl_log_globals
      [ 46%] Built target absl_random_internal_pool_urbg
      [ 47%] Built target absl_synchronization
      [ 47%] Built target absl_crc_cord_state
      [ 47%] Built target absl_log_internal_format
      [ 47%] Built target absl_log_sink
      [ 47%] Built target absl_random_seed_sequences
      [ 47%] Built target absl_flags_program_name
      [ 47%] Built target absl_hashtablez_sampler
      [ 47%] Built target absl_cord_internal
      [ 47%] Built target absl_cordz_handle
      [ 49%] Built target absl_raw_hash_set
      [ 49%] Built target absl_log_internal_log_sink_set
      [ 49%] Built target absl_flags_config
      [ 49%] Built target absl_cordz_info
      [ 49%] Built target absl_log_internal_message
      [ 49%] Built target absl_flags_internal
      [ 49%] Built target absl_cord
      [ 49%] Built target absl_log_internal_check_op
      [ 49%] Built target absl_status
      [ 49%] Built target absl_flags_reflection
      [ 49%] Built target absl_statusor
      [ 50%] Built target gpr
      [ 50%] Built target absl_flags
      [ 52%] Building CXX object mjpc/CMakeFiles/libmjpc.dir/agent.cc.o
      [ 52%] Building CXX object mjpc/CMakeFiles/libmjpc.dir/tasks/manipulation/common.cc.o
      [ 52%] Built target absl_flags_usage_internal
      [ 52%] Built target absl_flags_usage
      [ 52%] Building CXX object _deps/abseil-cpp-build/absl/flags/CMakeFiles/absl_flags_parse.dir/parse.cc.o
      [ 52%] Building CXX object mjpc/CMakeFiles/libmjpc.dir/tasks/manipulation/manipulation.cc.o
      [ 93%] Built target grpc
      [ 98%] Built target grpc++
      [ 98%] Running gRPC C++ protocol buffer compiler for src/proto/grpc/reflection/v1alpha/reflection.proto
      Scanning dependencies of target grpc++_reflection
      [ 98%] Building CXX object _deps/grpc-build/CMakeFiles/grpc++_reflection.dir/__/__/gens/src/proto/grpc/reflection/v1alpha/reflection.pb.cc.o
      /home/jsun/Mo/mujoco_mpc/mjpc/agent.cc: In member function ‘void mjpc::Agent::GUI(mjUI&)’:
      /home/jsun/Mo/mujoco_mpc/mjpc/agent.cc:597:65: error: no match for ‘operator=’ (operand types are ‘mjuiDef’ {aka ‘mjuiDef_’} and ‘<brace-enclosed initializer list>’)
        597 |                           DataAt(ActiveTask()->weight, i), "0 1"};
            |                                                                 ^
      In file included from /home/jsun/Mo/mujoco_mpc/build/_deps/mujoco-src/include/mujoco/mujoco.h:41,
                       from /home/jsun/Mo/mujoco_mpc/mjpc/../mjpc/agent.h:27,
                       from /home/jsun/Mo/mujoco_mpc/mjpc/agent.cc:15:
      /home/jsun/Mo/mujoco_mpc/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(const mjuiDef_&)’
        312 | struct mjuiDef_ {                 // table passed to mjui_add()
            |        ^~~~~~~~
      /home/jsun/Mo/mujoco_mpc/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const mjuiDef_&’
      /home/jsun/Mo/mujoco_mpc/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(mjuiDef_&&)’
      /home/jsun/Mo/mujoco_mpc/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘mjuiDef_&&’
      /home/jsun/Mo/mujoco_mpc/mjpc/agent.cc:616:65: error: no match for ‘operator=’ (operand types are ‘mjuiDef’ {aka ‘mjuiDef_’} and ‘<brace-enclosed initializer list>’)
        616 |     defFeatureParameters[0] = {mjITEM_SEPARATOR, "Parameters", 1};
            |                                                                 ^
      In file included from /home/jsun/Mo/mujoco_mpc/build/_deps/mujoco-src/include/mujoco/mujoco.h:41,
                       from /home/jsun/Mo/mujoco_mpc/mjpc/../mjpc/agent.h:27,
                       from /home/jsun/Mo/mujoco_mpc/mjpc/agent.cc:15:
      /home/jsun/Mo/mujoco_mpc/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(const mjuiDef_&)’
        312 | struct mjuiDef_ {                 // table passed to mjui_add()
            |        ^~~~~~~~
      /home/jsun/Mo/mujoco_mpc/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const mjuiDef_&’
      /home/jsun/Mo/mujoco_mpc/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(mjuiDef_&&)’
      /home/jsun/Mo/mujoco_mpc/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘mjuiDef_&&’
      /home/jsun/Mo/mujoco_mpc/mjpc/agent.cc:621:14: error: no match for ‘operator=’ (operand types are ‘mjuiDef’ {aka ‘mjuiDef_’} and ‘<brace-enclosed initializer list>’)
        621 |         "0 1"};
            |              ^
      In file included from /home/jsun/Mo/mujoco_mpc/build/_deps/mujoco-src/include/mujoco/mujoco.h:41,
                       from /home/jsun/Mo/mujoco_mpc/mjpc/../mjpc/agent.h:27,
                       from /home/jsun/Mo/mujoco_mpc/mjpc/agent.cc:15:
      /home/jsun/Mo/mujoco_mpc/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(const mjuiDef_&)’
        312 | struct mjuiDef_ {                 // table passed to mjui_add()
            |        ^~~~~~~~
      /home/jsun/Mo/mujoco_mpc/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const mjuiDef_&’
      /home/jsun/Mo/mujoco_mpc/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(mjuiDef_&&)’
      /home/jsun/Mo/mujoco_mpc/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘mjuiDef_&&’
      [ 98%] Building CXX object mjpc/CMakeFiles/libmjpc.dir/tasks/panda/panda.cc.o
      make[3]: *** [mjpc/CMakeFiles/libmjpc.dir/build.make:76：mjpc/CMakeFiles/libmjpc.dir/agent.cc.o] 错误 1
      make[3]: *** 正在等待未完成的任务....
      [ 98%] Building CXX object _deps/grpc-build/CMakeFiles/grpc++_reflection.dir/__/__/gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc.o
      [ 98%] Linking CXX static library ../../../../lib/libabsl_flags_parse.a
      [ 98%] Built target absl_flags_parse
      [ 98%] Building CXX object _deps/grpc-build/CMakeFiles/grpc++_reflection.dir/src/cpp/ext/proto_server_reflection.cc.o
      [ 98%] Building CXX object _deps/grpc-build/CMakeFiles/grpc++_reflection.dir/src/cpp/ext/proto_server_reflection_plugin.cc.o
      make[2]: *** [CMakeFiles/Makefile2:6316：mjpc/CMakeFiles/libmjpc.dir/all] 错误 2
      make[2]: *** 正在等待未完成的任务....
      [ 98%] Linking CXX static library ../../lib/libgrpc++_reflection.a
      [ 98%] Built target grpc++_reflection
      make[1]: *** [CMakeFiles/Makefile2:6772：mjpc/grpc/CMakeFiles/agent_server.dir/rule] 错误 2
      make: *** [Makefile:1916：agent_server] 错误 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/jsun/Mo/mujoco_mpc/python/setup.py", line 256, in <module>
          setuptools.setup(
        File "/home/jsun/Mo/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/jsun/Mo/venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/jsun/Mo/venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/jsun/Mo/venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/jsun/Mo/venv/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/jsun/Mo/venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/jsun/Mo/venv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/home/jsun/Mo/venv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/jsun/Mo/venv/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/jsun/Mo/venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/jsun/Mo/venv/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/jsun/Mo/venv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/jsun/Mo/venv/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/jsun/Mo/venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/jsun/Mo/mujoco_mpc/python/setup.py", line 199, in run
          self._configure_and_build_agent_server()
        File "/home/jsun/Mo/mujoco_mpc/python/setup.py", line 240, in _configure_and_build_agent_server
          subprocess.check_call(
        File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '/home/jsun/Mo/mujoco_mpc/build', '--target', 'agent_server', 'ui_agent_server', '-j4', '--config', 'Debug']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mujoco-mpc
  Running setup.py clean for mujoco-mpc
Failed to build mujoco-mpc
ERROR: Could not build wheels for mujoco-mpc, which is required to install pyproject.toml-based projects
```

**Comment by juju0111** [comment]
How did you clear this error ????? I got same error. Please help..!

**Comment by franciswoo** [comment]
This is probably a problem with the compiler version. Please upgrade the version of gcc g++ to 11 or higher.
